import { Product, BuildingCluster, Supplier } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  // =================== 1. FLOURS & GRAINS ===================
  {
    id: 'flour-aashirvaad-10kg',
    name: 'Aashirvaad Whole Wheat Chakki Atta',
    hindiName: 'चक्की आटा',
    category: 'flours',
    brand: 'Aashirvaad',
    unit: '10 kg sack',
    weightKg: 10.0,
    retailPriceNOK: 310,
    wholesalePriceNOK: 175,
    clubPriceNOK: 225,
    savingsNOK: 85,
    savingsPercent: 27,
    badge: 'Bestseller',
    emoji: '🌾',
    description: '100% whole wheat flour with dietary fiber and natural aroma. Premium MP Sharbati grains.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'flour-aashirvaad-5kg',
    name: 'Aashirvaad Whole Wheat Chakki Atta',
    hindiName: 'चक्की आटा (5kg)',
    category: 'flours',
    brand: 'Aashirvaad',
    unit: '5 kg sack',
    weightKg: 5.0,
    retailPriceNOK: 170,
    wholesalePriceNOK: 95,
    clubPriceNOK: 125,
    savingsNOK: 45,
    savingsPercent: 26,
    emoji: '🌾',
    description: 'Fresh chakki ground whole wheat flour in convenient 5kg bag.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'flour-besan-2kg',
    name: 'Rajdhani Pure Gram Flour (Besan)',
    hindiName: 'बेसन',
    category: 'flours',
    brand: 'Rajdhani / TRS',
    unit: '2 kg pack',
    weightKg: 2.0,
    retailPriceNOK: 85,
    wholesalePriceNOK: 46,
    clubPriceNOK: 62,
    savingsNOK: 23,
    savingsPercent: 27,
    emoji: '🟡',
    description: 'Finely milled 100% chana dal flour for pakoras, kadhi, and traditional sweets.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'flour-sooji-1kg',
    name: 'Roasted Sooji / Rava (Semolina)',
    hindiName: 'भुनी हुई सूजी / रवा',
    category: 'flours',
    brand: 'Swarna / Natco',
    unit: '1 kg pack',
    weightKg: 1.0,
    retailPriceNOK: 48,
    wholesalePriceNOK: 24,
    clubPriceNOK: 34,
    savingsNOK: 14,
    savingsPercent: 29,
    emoji: '🥣',
    description: 'Pre-roasted semolina for quick upma, halwa, and rava dosa without clumping.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'flour-poha-1kg',
    name: 'Haldiram Thick Poha (Flattened Rice)',
    hindiName: 'मोटा पोहा',
    category: 'flours',
    brand: 'Haldiram',
    unit: '1 kg pack',
    weightKg: 1.0,
    retailPriceNOK: 55,
    wholesalePriceNOK: 28,
    clubPriceNOK: 38,
    savingsNOK: 17,
    savingsPercent: 31,
    emoji: '🥣',
    description: 'High quality flattened rice flakes, perfect for quick breakfast kanda poha.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'flour-sabudana-1kg',
    name: 'Premium Sabudana (Tapioca Sago)',
    hindiName: 'साबूदाना',
    category: 'flours',
    brand: 'Heera / Natco',
    unit: '1 kg pack',
    weightKg: 1.0,
    retailPriceNOK: 65,
    wholesalePriceNOK: 32,
    clubPriceNOK: 45,
    savingsNOK: 20,
    savingsPercent: 31,
    emoji: '⚪',
    description: 'Pearled tapioca sago for non-sticky khichdi, vada, and kheer.',
    isPopular: false,
    inStock: true,
  },

  // =================== 2. PREMIUM RICE ===================
  {
    id: 'rice-indiagate-5kg',
    name: 'India Gate Classic Basmati Rice',
    hindiName: 'इंडिया गेट क्लासिक बासमती (5kg)',
    category: 'rice',
    brand: 'India Gate',
    unit: '5 kg sack',
    weightKg: 5.0,
    retailPriceNOK: 225,
    wholesalePriceNOK: 125,
    clubPriceNOK: 165,
    savingsNOK: 60,
    savingsPercent: 27,
    badge: 'Chef Favorite',
    emoji: '🍚',
    description: 'Aged 2 years. Extra long slender grains that do not stick, exquisite natural aroma.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'rice-daawat-10kg',
    name: 'Royal / Daawat Premium Basmati Rice',
    hindiName: 'दावत बासमती चावल (10kg)',
    category: 'rice',
    brand: 'Daawat / Royal',
    unit: '10 kg sack',
    weightKg: 10.0,
    retailPriceNOK: 390,
    wholesalePriceNOK: 225,
    clubPriceNOK: 295,
    savingsNOK: 95,
    savingsPercent: 24,
    badge: 'Super Bulk Value',
    emoji: '🍚',
    description: 'Bulk family pack of aged aromatic basmati rice for daily family meals and biryanis.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'rice-lalqilla-5kg',
    name: 'Lal Qilla Majestic Basmati Rice',
    hindiName: 'लाल किला मैजेस्टिक बासमती',
    category: 'rice',
    brand: 'Lal Qilla',
    unit: '5 kg sack',
    weightKg: 5.0,
    retailPriceNOK: 175,
    wholesalePriceNOK: 105,
    clubPriceNOK: 135,
    savingsNOK: 40,
    savingsPercent: 23,
    emoji: '🍚',
    description: 'Naturally fragrant Himalayan foothills basmati with sweet delicate texture.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'rice-sonamasoori-5kg',
    name: 'Sona Masoori Raw Rice (South Indian)',
    hindiName: 'सोना मसूरी चावल (5kg)',
    category: 'rice',
    brand: 'Priya / Royal',
    unit: '5 kg sack',
    weightKg: 5.0,
    retailPriceNOK: 185,
    wholesalePriceNOK: 110,
    clubPriceNOK: 145,
    savingsNOK: 40,
    savingsPercent: 22,
    emoji: '🍚',
    description: 'Lightweight, aromatic medium-grain rice ideal for sambar, rasam, and daily curd rice.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'rice-sonamasoori-10kg',
    name: 'Sona Masoori Raw Rice (South Indian)',
    hindiName: 'सोना मसूरी चावल (10kg)',
    category: 'rice',
    brand: 'Priya / Royal',
    unit: '10 kg sack',
    weightKg: 10.0,
    retailPriceNOK: 340,
    wholesalePriceNOK: 200,
    clubPriceNOK: 265,
    savingsNOK: 75,
    savingsPercent: 22,
    emoji: '🍚',
    description: 'Economy 10kg family sack of authentic Andhra/Karnataka Sona Masoori.',
    isPopular: false,
    inStock: true,
  },

  // =================== 3. LENTILS & PULSES (DAALS) ===================
  {
    id: 'dal-toor-2kg',
    name: 'Toor Dal / Arhar Dal (Yellow Pigeon Peas)',
    hindiName: 'तुवर / अरहर दाल',
    category: 'lentils',
    brand: 'Heera / TRS',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 98,
    wholesalePriceNOK: 52,
    clubPriceNOK: 72,
    savingsNOK: 26,
    savingsPercent: 27,
    badge: 'Daily Essential',
    emoji: '🍲',
    description: 'Polished yellow pigeon peas for comforting tadka dal, Gujarati khatti meethi dal, and sambar.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'dal-moong-2kg',
    name: 'Moong Dal Yellow Split (Dhuli)',
    hindiName: 'पीली मूंग दाल',
    category: 'lentils',
    brand: 'Heera / TRS',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 95,
    wholesalePriceNOK: 50,
    clubPriceNOK: 69,
    savingsNOK: 26,
    savingsPercent: 27,
    emoji: '🍲',
    description: 'Quick-cooking, easy-to-digest yellow lentils for khichdi and light homestyle curries.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'dal-chana-2kg',
    name: 'Chana Dal (Split Bengal Gram)',
    hindiName: 'चना दाल',
    category: 'lentils',
    brand: 'Heera / TRS',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 88,
    wholesalePriceNOK: 48,
    clubPriceNOK: 65,
    savingsNOK: 23,
    savingsPercent: 26,
    emoji: '🍲',
    description: 'Nutty, high-protein split chickpeas for dal fry, puran poli, and South Indian chutneys.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'dal-urad-2kg',
    name: 'Urad Dal Whole / Gota (White Washed)',
    hindiName: 'उड़द दाल गोटा (इडली/डोसा)',
    category: 'lentils',
    brand: 'TRS / Heera',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 115,
    wholesalePriceNOK: 60,
    clubPriceNOK: 82,
    savingsNOK: 33,
    savingsPercent: 29,
    badge: 'Idli / Dosa Must',
    emoji: '⚪',
    description: 'Whole dehusked urad dal with high mucilage, essential for fluffy idli and crispy dosa batter.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'dal-masoor-2kg',
    name: 'Masoor Dal (Red Split Lentils)',
    hindiName: 'लाल मसूर दाल',
    category: 'lentils',
    brand: 'Heera / TRS',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 85,
    wholesalePriceNOK: 45,
    clubPriceNOK: 62,
    savingsNOK: 23,
    savingsPercent: 27,
    emoji: '🍲',
    description: 'Fast-cooking red split lentils that melt into velvety rich comfort dal in 15 minutes.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'dal-rajma-2kg',
    name: 'Rajma Chitra (Red Kidney Beans)',
    hindiName: 'राजमा चित्रा',
    category: 'lentils',
    brand: 'Heera / TRS',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 105,
    wholesalePriceNOK: 55,
    clubPriceNOK: 76,
    savingsNOK: 29,
    savingsPercent: 28,
    emoji: '🫘',
    description: 'Speckled Chitra variety kidney beans that cook tender and absorb thick Punjabi gravy.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'dal-kabuli-2kg',
    name: 'Kabuli Chana (Large White Chickpeas)',
    hindiName: 'काबुली चना (छोले)',
    category: 'lentils',
    brand: 'Heera / TRS',
    unit: '2 kg bag',
    weightKg: 2.0,
    retailPriceNOK: 100,
    wholesalePriceNOK: 52,
    clubPriceNOK: 74,
    savingsNOK: 26,
    savingsPercent: 26,
    emoji: '🧆',
    description: 'Jumbo grade chickpeas with creamy interior, ideal for authentic Amritsari Chole.',
    isPopular: true,
    inStock: true,
  },

  // =================== 4. COOKING OILS & PURE GHEE ===================
  {
    id: 'oil-mustard-5l',
    name: 'KTC / Fortune Pure Mustard Oil',
    hindiName: 'सरसों का तेल (5L)',
    category: 'oils_ghee',
    brand: 'KTC / Fortune',
    unit: '5 L tin',
    weightKg: 4.6,
    retailPriceNOK: 215,
    wholesalePriceNOK: 115,
    clubPriceNOK: 155,
    savingsNOK: 60,
    savingsPercent: 28,
    badge: 'North Indian Staple',
    emoji: '🫒',
    description: 'Pungent cold-pressed mustard oil for authentic fish curries, bhindi, and homemade pickles.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'oil-mustard-2l',
    name: 'KTC / Fortune Pure Mustard Oil',
    hindiName: 'सरसों का तेल (2L)',
    category: 'oils_ghee',
    brand: 'KTC / Fortune',
    unit: '2 L bottle',
    weightKg: 1.85,
    retailPriceNOK: 95,
    wholesalePriceNOK: 55,
    clubPriceNOK: 72,
    savingsNOK: 23,
    savingsPercent: 24,
    emoji: '🫒',
    description: 'Authentic pure mustard oil in easy-pour 2 liter bottle.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'oil-sunflower-5l',
    name: 'Pure Refined Sunflower Oil',
    hindiName: 'सूरजमुखी तेल (5L)',
    category: 'oils_ghee',
    brand: 'KTC / EuroChef',
    unit: '5 L jug',
    weightKg: 4.6,
    retailPriceNOK: 195,
    wholesalePriceNOK: 105,
    clubPriceNOK: 145,
    savingsNOK: 50,
    savingsPercent: 26,
    emoji: '🌻',
    description: 'Neutral aroma, high smoke-point cooking oil for daily deep frying, puris, and tadka.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'oil-peanut-5l',
    name: 'Groundnut (Peanut) Cooking Oil',
    hindiName: 'मूंगफली का तेल (5L)',
    category: 'oils_ghee',
    brand: 'KTC / Natco',
    unit: '5 L can',
    weightKg: 4.6,
    retailPriceNOK: 235,
    wholesalePriceNOK: 135,
    clubPriceNOK: 175,
    savingsNOK: 60,
    savingsPercent: 26,
    emoji: '🥜',
    description: 'Nutty rich aroma preferred in Maharashtrian, Gujarati, and South Indian cooking.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'oil-sesame-1l',
    name: 'Idhayam Pure Gingelly (Sesame) Oil',
    hindiName: 'तिल का तेल (इधायम 1L)',
    category: 'oils_ghee',
    brand: 'Idhayam',
    unit: '1 L bottle',
    weightKg: 0.95,
    retailPriceNOK: 95,
    wholesalePriceNOK: 52,
    clubPriceNOK: 69,
    savingsNOK: 26,
    savingsPercent: 27,
    badge: 'South Indian Essential',
    emoji: '🫙',
    description: 'Cold-pressed traditional gingelly oil with palm jaggery, irreplaceable for authentic South Indian dishes.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'oil-coconut-1l',
    name: 'KLF Coconad Pure Edible Coconut Oil',
    hindiName: 'नारियल का तेल (1L)',
    category: 'oils_ghee',
    brand: 'KLF Coconad / Parachute',
    unit: '1 L bottle',
    weightKg: 0.92,
    retailPriceNOK: 85,
    wholesalePriceNOK: 45,
    clubPriceNOK: 62,
    savingsNOK: 23,
    savingsPercent: 27,
    emoji: '🥥',
    description: '100% roasted Kerala coconut oil for avial, thoran, and fish curries.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'ghee-amul-1l',
    name: 'Amul Pure Desi Ghee',
    hindiName: 'अमुल शुद्ध देसी घी (1L)',
    category: 'oils_ghee',
    brand: 'Amul',
    unit: '1 L tin',
    weightKg: 1.0,
    retailPriceNOK: 240,
    wholesalePriceNOK: 135,
    clubPriceNOK: 180,
    savingsNOK: 60,
    savingsPercent: 25,
    badge: 'Gold Standard',
    emoji: '🧈',
    description: 'The taste of India. Pure clarified milk butterfat with rich granular texture and nostalgic aroma.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'ghee-amul-5l',
    name: 'Amul Pure Desi Ghee (Bulk 5 L Tin)',
    hindiName: 'अमुल शुद्ध देसी घी (5L थोक टिन)',
    category: 'oils_ghee',
    brand: 'Amul',
    unit: '5 L tin',
    weightKg: 4.8,
    retailPriceNOK: 1050,
    wholesalePriceNOK: 610,
    clubPriceNOK: 790,
    savingsNOK: 260,
    savingsPercent: 25,
    badge: 'Save 260 NOK',
    emoji: '🧈',
    description: 'Mega bulk catering tin of authentic Amul ghee. Maximum value for large families and sweet makers.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'ghee-aashirvaad-1l',
    name: 'Aashirvaad Svasti Pure Cow Ghee',
    hindiName: 'आशीर्वाद स्वस्ति गाय का घी (1L)',
    category: 'oils_ghee',
    brand: 'Aashirvaad',
    unit: '1 L jar',
    weightKg: 1.0,
    retailPriceNOK: 245,
    wholesalePriceNOK: 140,
    clubPriceNOK: 185,
    savingsNOK: 60,
    savingsPercent: 24,
    emoji: '🧈',
    description: 'Specially crafted golden cow ghee using slow-cooking process for deep aroma.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'ghee-khanum-1kg',
    name: 'Khanum Pure Butter Ghee',
    hindiName: 'खानम शुद्ध मक्खन घी (1kg)',
    category: 'oils_ghee',
    brand: 'Khanum',
    unit: '1 kg tin',
    weightKg: 1.0,
    retailPriceNOK: 225,
    wholesalePriceNOK: 125,
    clubPriceNOK: 170,
    savingsNOK: 55,
    savingsPercent: 24,
    emoji: '🧈',
    description: 'Finest quality clarified butterfat widely trusted across the European South Asian diaspora.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'ghee-khanum-2kg',
    name: 'Khanum Pure Butter Ghee',
    hindiName: 'खानम शुद्ध मक्खन घी (2kg)',
    category: 'oils_ghee',
    brand: 'Khanum',
    unit: '2 kg tin',
    weightKg: 2.0,
    retailPriceNOK: 395,
    wholesalePriceNOK: 220,
    clubPriceNOK: 295,
    savingsNOK: 100,
    savingsPercent: 25,
    emoji: '🧈',
    description: 'Double size 2kg tin offering great economy for regular roti brushing and parathas.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'ghee-grb-1l',
    name: 'GRB Dairy Desi Ghee (Aromatic Granular)',
    hindiName: 'जीआरबी शुद्ध घी (1L)',
    category: 'oils_ghee',
    brand: 'GRB',
    unit: '1 L bottle',
    weightKg: 1.0,
    retailPriceNOK: 230,
    wholesalePriceNOK: 130,
    clubPriceNOK: 175,
    savingsNOK: 55,
    savingsPercent: 24,
    emoji: '🧈',
    description: 'Renowned for its distinct granular (danedaar) texture and South Indian filter coffee aroma.',
    isPopular: false,
    inStock: true,
  },

  // =================== 5. SPICES & SEASONINGS ===================
  {
    id: 'spice-mdh-combo-4pk',
    name: 'MDH Spice Mixes (Biryani, Chana, Garam, Kitchen King)',
    hindiName: 'एमडीएच मसाला कॉम्बो (4 डिब्बे)',
    category: 'spices',
    brand: 'MDH',
    unit: '4 x 100g boxes',
    weightKg: 0.45,
    retailPriceNOK: 152,
    wholesalePriceNOK: 72,
    clubPriceNOK: 99,
    savingsNOK: 53,
    savingsPercent: 35,
    badge: 'Combo Savings',
    emoji: '🌶️',
    description: 'Set of 4 essential MDH masala boxes: Biryani Masala, Chana Masala, Garam Masala, Kitchen King.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'spice-shan-combo-4pk',
    name: 'Shan Recipe Mixes (Special Biryani, Korma, Nihari, Haleem)',
    hindiName: 'शान मसाला कॉम्बो (4 डिब्बे)',
    category: 'spices',
    brand: 'Shan',
    unit: '4 x 100g boxes',
    weightKg: 0.45,
    retailPriceNOK: 152,
    wholesalePriceNOK: 72,
    clubPriceNOK: 99,
    savingsNOK: 53,
    savingsPercent: 35,
    badge: 'Popular',
    emoji: '🌶️',
    description: '4 iconic Pakistani/Desi recipe mixes formulated with whole and ground aromatic spices.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'spice-jeera-500g',
    name: 'Whole Cumin Seeds (Jeera)',
    hindiName: 'साबुत जीरा (500g)',
    category: 'spices',
    brand: 'TRS / MDH',
    unit: '500 g pouch',
    weightKg: 0.5,
    retailPriceNOK: 85,
    wholesalePriceNOK: 42,
    clubPriceNOK: 58,
    savingsNOK: 27,
    savingsPercent: 32,
    emoji: '🌿',
    description: 'Selected bold cumin seeds with intense earthy aroma for essential everyday tadka.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'spice-mustard-500g',
    name: 'Brown Mustard Seeds (Rai / Sarson)',
    hindiName: 'राई / सरसों दाना (500g)',
    category: 'spices',
    brand: 'TRS / Heera',
    unit: '500 g pouch',
    weightKg: 0.5,
    retailPriceNOK: 65,
    wholesalePriceNOK: 32,
    clubPriceNOK: 45,
    savingsNOK: 20,
    savingsPercent: 31,
    emoji: '⚫',
    description: 'Small pungent brown mustard seeds for crackling South Indian and Bengali tempering.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'spice-cardamom-100g',
    name: 'Green Cardamom (Hari Elaichi)',
    hindiName: 'हरी इलायची (100g)',
    category: 'spices',
    brand: 'Heera / Natco',
    unit: '100 g pouch',
    weightKg: 0.1,
    retailPriceNOK: 75,
    wholesalePriceNOK: 40,
    clubPriceNOK: 54,
    savingsNOK: 21,
    savingsPercent: 28,
    emoji: '🌱',
    description: 'Bold fragrant green cardamom pods for masala chai, biryanis, and Indian desserts.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'spice-haldi-500g',
    name: 'Pure Turmeric Powder (Haldi)',
    hindiName: 'हल्दी पाउडर (500g)',
    category: 'spices',
    brand: 'MDH / TRS',
    unit: '500 g pack',
    weightKg: 0.5,
    retailPriceNOK: 60,
    wholesalePriceNOK: 30,
    clubPriceNOK: 42,
    savingsNOK: 18,
    savingsPercent: 30,
    emoji: '💛',
    description: 'High curcumin golden turmeric powder with no added fillers or food coloring.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'spice-deggimirch-500g',
    name: 'MDH Deggi Mirch (Kashmiri Chili Powder)',
    hindiName: 'देगी मिर्च (500g)',
    category: 'spices',
    brand: 'MDH',
    unit: '500 g pack',
    weightKg: 0.5,
    retailPriceNOK: 75,
    wholesalePriceNOK: 38,
    clubPriceNOK: 52,
    savingsNOK: 23,
    savingsPercent: 31,
    emoji: '🔴',
    description: 'Gives rich natural red color without overpowering fiery heat to gravies and tikkas.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'spice-kasurimethi-100g',
    name: 'Kasuri Methi (Dried Fenugreek Leaves)',
    hindiName: 'कस्तूरी मेथी (100g)',
    category: 'spices',
    brand: 'MDH / Shan',
    unit: '100 g box',
    weightKg: 0.1,
    retailPriceNOK: 42,
    wholesalePriceNOK: 20,
    clubPriceNOK: 29,
    savingsNOK: 13,
    savingsPercent: 31,
    emoji: '🍃',
    description: 'Sun-dried aromatic fenugreek leaves that elevate butter paneer and dal makhani.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'spice-hing-100g',
    name: 'LG Compounded Asafoetida (Hing)',
    hindiName: 'एलजी हींग (100g)',
    category: 'spices',
    brand: 'LG',
    unit: '100 g tub',
    weightKg: 0.1,
    retailPriceNOK: 45,
    wholesalePriceNOK: 22,
    clubPriceNOK: 32,
    savingsNOK: 13,
    savingsPercent: 29,
    emoji: '🧅',
    description: 'A pinch transforms dal and sambar with deep umami aroma. Natural digestive aid.',
    isPopular: false,
    inStock: true,
  },

  // =================== 6. BREAKFAST & INSTANT MIXES ===================
  {
    id: 'mix-mtr-dosa-500g',
    name: 'MTR Instant Dosa Ready-Mix',
    hindiName: 'एमटीआर डोसा मिक्स (500g)',
    category: 'breakfast_mixes',
    brand: 'MTR',
    unit: '500 g pack',
    weightKg: 0.5,
    retailPriceNOK: 58,
    wholesalePriceNOK: 30,
    clubPriceNOK: 42,
    savingsNOK: 16,
    savingsPercent: 28,
    badge: 'Quick Breakfast',
    emoji: '🥞',
    description: 'Makes ~12-14 crispy restaurant-style dosas in minutes. Just mix with water & sour curd.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'mix-mtr-ravaidli-500g',
    name: 'MTR Rava Idli Ready-Mix',
    hindiName: 'एमटीआर रवा इडली मिक्स (500g)',
    category: 'breakfast_mixes',
    brand: 'MTR',
    unit: '500 g pack',
    weightKg: 0.5,
    retailPriceNOK: 58,
    wholesalePriceNOK: 30,
    clubPriceNOK: 42,
    savingsNOK: 16,
    savingsPercent: 28,
    emoji: '🍥',
    description: 'Famous Bangalore recipe with cashews, mustard seeds, and ginger. Steams fluffy in 10 mins.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'mix-gits-gulabjamun-500g',
    name: 'Gits Instant Gulab Jamun Mix',
    hindiName: 'गिट्स गुलाब जामुन मिक्स (500g)',
    category: 'breakfast_mixes',
    brand: 'Gits',
    unit: '500 g pack',
    weightKg: 0.5,
    retailPriceNOK: 68,
    wholesalePriceNOK: 34,
    clubPriceNOK: 48,
    savingsNOK: 20,
    savingsPercent: 29,
    emoji: '🧆',
    description: 'Makes ~40 soft, melt-in-mouth gulab jamuns. Perfect for weekend gatherings and festivals.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'mix-vermicelli-400g',
    name: 'Bambino Roasted Vermicelli (Seviyan)',
    hindiName: 'बाम्बीनो भुनी सेवइयां (400g)',
    category: 'breakfast_mixes',
    brand: 'Bambino',
    unit: '400 g pack',
    weightKg: 0.4,
    retailPriceNOK: 32,
    wholesalePriceNOK: 16,
    clubPriceNOK: 23,
    savingsNOK: 9,
    savingsPercent: 28,
    emoji: '🍜',
    description: 'Pre-roasted durum wheat vermicelli for sweet sheer khurma, kheer, and savory upma.',
    isPopular: false,
    inStock: true,
  },

  // =================== 7. SNACKS, SWEETS & BISCUITS ===================
  {
    id: 'snack-haldiram-aloobhujia-400g',
    name: 'Haldiram Aloo Bhujia',
    hindiName: 'हल्दीराम आलू भुजिया (400g)',
    category: 'snacks',
    brand: 'Haldiram',
    unit: '400 g pack',
    weightKg: 0.4,
    retailPriceNOK: 65,
    wholesalePriceNOK: 32,
    clubPriceNOK: 46,
    savingsNOK: 19,
    savingsPercent: 29,
    badge: '#1 Desi Snack',
    emoji: '🥨',
    description: 'Crispy spicy potato and gram flour noodles flavored with mint and signature spices.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'snack-haldiram-khattameetha-400g',
    name: 'Haldiram Khatta Meetha Mixture',
    hindiName: 'हल्दीराम खट्टा मीठा (400g)',
    category: 'snacks',
    brand: 'Haldiram',
    unit: '400 g pack',
    weightKg: 0.4,
    retailPriceNOK: 65,
    wholesalePriceNOK: 32,
    clubPriceNOK: 46,
    savingsNOK: 19,
    savingsPercent: 29,
    emoji: '🍿',
    description: 'Sweet and tangy blend of chickpea flour sev, puffed rice, green peas, and peanuts.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'snack-kurkure-masala-115g',
    name: 'Kurkure Masala Munch (Pack of 2)',
    hindiName: 'कुरकुरे मसाला मंच (2 पैकेट)',
    category: 'snacks',
    brand: 'Kurkure',
    unit: '2 x 115g bags',
    weightKg: 0.25,
    retailPriceNOK: 56,
    wholesalePriceNOK: 28,
    clubPriceNOK: 40,
    savingsNOK: 16,
    savingsPercent: 29,
    emoji: '🍟',
    description: 'Tedha hai par mera hai! Crunchy corn puffs dusted with fiery Indian masala blend.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'snack-banana-chips-250g',
    name: 'Kerala Style Banana Chips (Coconut Oil Fried)',
    hindiName: 'केरल केला वेफर्स (250g)',
    category: 'snacks',
    brand: 'Grandma / Aachi',
    unit: '250 g bag',
    weightKg: 0.25,
    retailPriceNOK: 52,
    wholesalePriceNOK: 26,
    clubPriceNOK: 36,
    savingsNOK: 16,
    savingsPercent: 31,
    emoji: '🍌',
    description: 'Crispy raw Nendran bananas thinly sliced and fried in pure coconut oil with black pepper.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'snack-soanpapdi-500g',
    name: 'Haldiram Soan Papdi (Desi Ghee)',
    hindiName: 'सोन पापड़ी (500g)',
    category: 'snacks',
    brand: 'Haldiram',
    unit: '500 g box',
    weightKg: 0.5,
    retailPriceNOK: 72,
    wholesalePriceNOK: 36,
    clubPriceNOK: 50,
    savingsNOK: 22,
    savingsPercent: 31,
    emoji: '🍬',
    description: 'Flaky, melt-in-mouth traditional gram flour sweet topped with pistachios and almonds.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'biscuit-parleg-800g',
    name: 'Parle-G Original Glucose Biscuits',
    hindiName: 'पारले-जी बिस्कुट (800g फैमिली पैक)',
    category: 'snacks',
    brand: 'Parle',
    unit: '800 g Family Pack',
    weightKg: 0.8,
    retailPriceNOK: 52,
    wholesalePriceNOK: 26,
    clubPriceNOK: 37,
    savingsNOK: 15,
    savingsPercent: 29,
    badge: 'Chai Partner',
    emoji: '🍪',
    description: 'The world’s largest selling biscuit. Timeless sweet wheat flavor crafted for chai dipping.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'biscuit-goodday-8pk',
    name: 'Britannia Good Day Butter Cookies',
    hindiName: 'गुड डे बटर कुकीज (8 पैक)',
    category: 'snacks',
    brand: 'Britannia',
    unit: 'Pack of 8 (8x75g)',
    weightKg: 0.6,
    retailPriceNOK: 75,
    wholesalePriceNOK: 38,
    clubPriceNOK: 52,
    savingsNOK: 23,
    savingsPercent: 31,
    emoji: '🍪',
    description: 'Rich buttery cookies with a cheerful smile pattern. Bulk multipack for family teatime.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'snack-kcb-tearusks-400g',
    name: 'KCB Round Crispy Tea Rusks',
    hindiName: 'केसीबी टी रस्क (400g)',
    category: 'snacks',
    brand: 'KCB (Kashmir Crown)',
    unit: '400 g bag',
    weightKg: 0.4,
    retailPriceNOK: 40,
    wholesalePriceNOK: 22,
    clubPriceNOK: 30,
    savingsNOK: 10,
    savingsPercent: 25,
    emoji: '🍞',
    description: 'Double-baked crunchy round toasts engineered to soak up hot milk and cardamom tea.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'snack-kcb-cakerusks-600g',
    name: 'KCB Premium Cake Rusks (with Fennel)',
    hindiName: 'केसीबी केक रस्क (600g)',
    category: 'snacks',
    brand: 'KCB (Kashmir Crown)',
    unit: '600 g pack',
    weightKg: 0.6,
    retailPriceNOK: 100,
    wholesalePriceNOK: 55,
    clubPriceNOK: 75,
    savingsNOK: 25,
    savingsPercent: 25,
    emoji: '🍞',
    description: 'Double-baked sponge cake infused with whole saunf (fennel seeds). 26 golden slices.',
    isPopular: false,
    inStock: true,
  },

  // =================== 8. PICKLES & CHUTNEYS (GLASS BOTTLES) ===================
  {
    id: 'pickle-mothers-mango-500g',
    name: "Mother's Recipe Mango Pickle",
    hindiName: 'आम का अचार (500g)',
    category: 'pickles',
    brand: "Mother's Recipe",
    unit: '500 g glass jar',
    weightKg: 0.75,
    retailPriceNOK: 58,
    wholesalePriceNOK: 26,
    clubPriceNOK: 39,
    savingsNOK: 19,
    savingsPercent: 33,
    badge: 'Glass Jar',
    isGlassJar: true,
    emoji: '🥭',
    description: 'Spicy mustard oil pickle with tender raw green mango wedges and fenugreek seeds.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'pickle-mothers-mixed-500g',
    name: "Mother's Recipe Mixed Pickle",
    hindiName: 'मिक्स अचार (500g)',
    category: 'pickles',
    brand: "Mother's Recipe",
    unit: '500 g glass jar',
    weightKg: 0.75,
    retailPriceNOK: 58,
    wholesalePriceNOK: 26,
    clubPriceNOK: 39,
    savingsNOK: 19,
    savingsPercent: 33,
    isGlassJar: true,
    emoji: '🫙',
    description: 'Crowd-pleasing blend of mango, lime, carrot, and green chili marinated in mustard oil.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'pickle-shan-lime-500g',
    name: 'Shan / Priya Lime Pickle in Oil',
    hindiName: 'नींबू का अचार (500g)',
    category: 'pickles',
    brand: 'Shan / Priya',
    unit: '500 g glass jar',
    weightKg: 0.75,
    retailPriceNOK: 58,
    wholesalePriceNOK: 26,
    clubPriceNOK: 39,
    savingsNOK: 19,
    savingsPercent: 33,
    isGlassJar: true,
    emoji: '🍋',
    description: 'Zesty, tongue-tickling sour lime wedges cured with whole spices and chili.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'pickle-priya-greenchilli-500g',
    name: 'Priya Hot Green Chilli Pickle (with Garlic)',
    hindiName: 'हरी मिर्च लहसुन का अचार (500g)',
    category: 'pickles',
    brand: 'Priya',
    unit: '500 g glass jar',
    weightKg: 0.75,
    retailPriceNOK: 62,
    wholesalePriceNOK: 28,
    clubPriceNOK: 42,
    savingsNOK: 20,
    savingsPercent: 32,
    isGlassJar: true,
    emoji: '🌶️',
    description: 'Authentic Telugu-style spicy green chili pickle with whole garlic pods. High heat!',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'pickle-ahmed-mixed-1kg',
    name: 'Ahmed Foods Mixed Pickle in Oil (Jumbo 1kg)',
    hindiName: 'अहमद मिक्स अचार (1kg बड़ा जार)',
    category: 'pickles',
    brand: 'Ahmed Foods',
    unit: '1 kg large jar',
    weightKg: 1.4,
    retailPriceNOK: 92,
    wholesalePriceNOK: 42,
    clubPriceNOK: 62,
    savingsNOK: 30,
    savingsPercent: 33,
    badge: 'Jumbo Size',
    isGlassJar: true,
    emoji: '🫙',
    description: 'Family size 1 kg jar of classic spicy subcontinental mixed pickle. Incredible value.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'paste-ginger-garlic-750g',
    name: 'Homestyle Ginger-Garlic Paste',
    hindiName: 'अदरक लहसुन पेस्ट (750g)',
    category: 'pickles',
    brand: "Mother's Recipe / Shan",
    unit: '750 g glass jar',
    weightKg: 1.05,
    retailPriceNOK: 65,
    wholesalePriceNOK: 30,
    clubPriceNOK: 45,
    savingsNOK: 20,
    savingsPercent: 31,
    isGlassJar: true,
    emoji: '🧄',
    description: '50:50 blend of freshly crushed ginger and garlic. Saves 15 minutes of prep on every curry.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'chutney-pataks-mango-340g',
    name: "Patak's Sweet Mango Chutney",
    hindiName: 'मीठी आम की चटनी (340g)',
    category: 'pickles',
    brand: "Patak's",
    unit: '340 g glass jar',
    weightKg: 0.55,
    retailPriceNOK: 62,
    wholesalePriceNOK: 28,
    clubPriceNOK: 42,
    savingsNOK: 20,
    savingsPercent: 32,
    isGlassJar: true,
    emoji: '🥭',
    description: 'Sweet, spiced mango dip spiced with whole nigella seeds and ginger. Perfect with samosas and papadums.',
    isPopular: false,
    inStock: true,
  },

  // =================== 9. AMBIENT BULK ROOT VEGETABLES ===================
  {
    id: 'veg-onion-5kg',
    name: 'Red Onions (Rødløk) Bulk Mesh Sack',
    hindiName: 'लाल प्याज (5kg बोरी)',
    category: 'root_vegetables',
    brand: 'Import Grade A',
    unit: '5 kg mesh bag',
    weightKg: 5.0,
    retailPriceNOK: 135,
    wholesalePriceNOK: 48,
    clubPriceNOK: 85,
    savingsNOK: 50,
    savingsPercent: 37,
    badge: 'Save 37%',
    emoji: '🧅',
    description: 'Firm, pungent red onions in breathable mesh sack. Kept dry, stores fresh for 3-4 weeks.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'veg-onion-10kg',
    name: 'Red Onions (Rødløk) Bulk Mesh Sack',
    hindiName: 'लाल प्याज (10kg बोरी)',
    category: 'root_vegetables',
    brand: 'Import Grade A',
    unit: '10 kg sack',
    weightKg: 10.0,
    retailPriceNOK: 250,
    wholesalePriceNOK: 85,
    clubPriceNOK: 150,
    savingsNOK: 100,
    savingsPercent: 40,
    badge: 'Save 100 NOK',
    emoji: '🧅',
    description: '10kg wholesale produce sack. Perfect for heavy curry bases, biryanis, and salads.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'veg-potato-5kg',
    name: 'Curry Potatoes (Poteter) Bulk Sack',
    hindiName: 'आलू (5kg बोरी)',
    category: 'root_vegetables',
    brand: 'Norske / EU Poteter',
    unit: '5 kg bag',
    weightKg: 5.0,
    retailPriceNOK: 110,
    wholesalePriceNOK: 42,
    clubPriceNOK: 72,
    savingsNOK: 38,
    savingsPercent: 35,
    emoji: '🥔',
    description: 'All-purpose firm potatoes for aloo gobi, samosa fillings, and rich potato curries.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'veg-potato-10kg',
    name: 'Curry Potatoes (Poteter) Bulk Sack',
    hindiName: 'आलू (10kg बोरी)',
    category: 'root_vegetables',
    brand: 'Norske / EU Poteter',
    unit: '10 kg sack',
    weightKg: 10.0,
    retailPriceNOK: 210,
    wholesalePriceNOK: 78,
    clubPriceNOK: 135,
    savingsNOK: 75,
    savingsPercent: 36,
    emoji: '🥔',
    description: 'Bulk 10 kg paper sack of medium-firm potatoes. Long shelf life when kept dark and cool.',
    isPopular: false,
    inStock: true,
  },
  {
    id: 'veg-garlic-1kg',
    name: 'Fresh White Garlic (Hvitløk)',
    hindiName: 'लहसुन (1kg जाली)',
    category: 'root_vegetables',
    brand: 'Grade A Import',
    unit: '1 kg net',
    weightKg: 1.0,
    retailPriceNOK: 75,
    wholesalePriceNOK: 32,
    clubPriceNOK: 49,
    savingsNOK: 26,
    savingsPercent: 35,
    badge: 'Great Value',
    emoji: '🧄',
    description: 'Tight-skinned white garlic bulbs in 1kg net. Massive savings over 3-bulb supermarket packs.',
    isPopular: true,
    inStock: true,
  },
  {
    id: 'veg-ginger-1kg',
    name: 'Fresh Whole Ginger Root (Ingefær)',
    hindiName: 'ताजा अदरक (1kg)',
    category: 'root_vegetables',
    brand: 'Fresh Import',
    unit: '1 kg bag',
    weightKg: 1.0,
    retailPriceNOK: 95,
    wholesalePriceNOK: 42,
    clubPriceNOK: 62,
    savingsNOK: 33,
    savingsPercent: 35,
    emoji: '🫚',
    description: 'Plump, fiber-rich fresh ginger root for daily morning chai and rich curry gravies.',
    isPopular: true,
    inStock: true,
  },
];

// Initial active building clusters in Oslo / Akershus
export const INITIAL_BUILDINGS: BuildingCluster[] = [
  {
    id: 'fornebu-portal',
    name: 'Fornebu Portal & Rolfsbuktveien',
    area: 'Fornebu / Snarøya (Bærum)',
    address: 'Rolfsbuktveien 17 / Snarøyveien, 1364 Fornebu',
    targetOrders: 10,
    currentOrders: 8,
    nextDeliveryDate: 'Saturday, Sep 13',
    pickupWindow: '10:30 – 11:15 AM',
    hostName: 'Amit & Priya S.',
    hostContact: '+47 912 34 567',
  },
  {
    id: 'lysaker-brygge',
    name: 'Lysaker Brygge Sameie',
    area: 'Lysaker (Bærum)',
    address: 'Lysaker Brygge 24–36, 1366 Lysaker',
    targetOrders: 8,
    currentOrders: 5,
    nextDeliveryDate: 'Saturday, Sep 13',
    pickupWindow: '11:45 AM – 12:30 PM',
    hostName: 'Karthik R.',
    hostContact: '+47 481 23 890',
  },
  {
    id: 'lillestrom-stasjon',
    name: 'Lillestrøm Stasjonsby Borettslag',
    area: 'Lillestrøm',
    address: 'Kanalveien 12–18, 2000 Lillestrøm',
    targetOrders: 10,
    currentOrders: 9,
    nextDeliveryDate: 'Saturday, Sep 13',
    pickupWindow: '1:15 – 2:00 PM',
    hostName: 'Vikram & Sunita M.',
    hostContact: '+47 934 56 789',
  },
  {
    id: 'lorenskog-skarer',
    name: 'Lørenskog Sentrum / Skårersletta',
    area: 'Lørenskog',
    address: 'Skårersletta 45, 1473 Lørenskog',
    targetOrders: 8,
    currentOrders: 6,
    nextDeliveryDate: 'Saturday, Sep 13',
    pickupWindow: '2:30 – 3:15 PM',
    hostName: 'Rahul P.',
    hostContact: '+47 465 78 912',
  },
  {
    id: 'storo-nydalen',
    name: 'Storo & Nydalen Kvartal',
    area: 'Oslo North (Storo/Nydalen)',
    address: 'Vitaminveien 7 / Gunnar Schjelderups vei, 0485 Oslo',
    targetOrders: 8,
    currentOrders: 4,
    nextDeliveryDate: 'Saturday, Sep 13',
    pickupWindow: '3:45 – 4:30 PM',
    hostName: 'Deepak T.',
    hostContact: '+47 998 12 345',
  },
  {
    id: 'sandvika-fjordalleen',
    name: 'Sandvika Fjordalléen Borettslag',
    area: 'Sandvika (Bærum)',
    address: 'Fjordalléen 8, 1338 Sandvika',
    targetOrders: 8,
    currentOrders: 7,
    nextDeliveryDate: 'Saturday, Sep 13',
    pickupWindow: '9:30 – 10:15 AM',
    hostName: 'Sneha & Rajesh K.',
    hostContact: '+47 412 89 012',
  },
];

// Verified Norwegian Wholesalers Directory
export const NORWAY_SUPPLIERS: Supplier[] = [
  {
    id: 'abiramy-cash-carry',
    name: 'Abiramy Cash & Carry',
    categoryBadge: 'Cash & Carry / Wholesale',
    address: 'Veitvetveien 8, 0596 Oslo (Veitvet Senter)',
    area: 'Veitvet / Groruddalen, Oslo',
    phone: '+47 902 72 500 / +47 22 25 32 64',
    email: 'faktura@abiramyoslo.no',
    openingHours: 'Mon–Thu: 10:00–21:00, Fri–Sat: 10:00–21:30, Sun: Closed',
    moqNotes: 'Full sacks/cartons. Bulk discounts start at 5–10 sacks of Atta/Rice.',
    specialties: [
      'Aashirvaad & Elephant Atta 10kg',
      'India Gate, Daawat & Royal Basmati 5kg/10kg/20kg',
      'TRS & Heera Daals (2kg, 5kg, 10kg)',
      'Ghee & Cooking Oils bulk tins',
      'Idhayam Sesame & KLF Coconut Oils',
    ],
    paymentTerms: 'Cash & Carry (Bank card / Vipps on-site) or B2B invoice for registered businesses.',
    mapsUrl: 'https://maps.google.com/?q=Veitvetveien+8+0596+Oslo',
    website: 'https://abiramyoslo.no',
    recommendedFor: 'Best primary supplier for heavy sacks of flour, basmati rice, lentils, and pure ghee tins.',
  },
  {
    id: 'scanasia',
    name: 'Scanasia AS',
    categoryBadge: 'Master Importer & B2B Wholesaler',
    address: 'Stanseveien 27, 0976 Oslo',
    area: 'Alnabru / Groruddalen, Oslo',
    phone: '+47 22 90 29 90',
    email: 'firmapost@scanasia.no',
    openingHours: 'Mon–Fri: 08:00–16:00, Sat–Sun: Closed',
    moqNotes: 'Pallet or master carton orders. Requires Norwegian business registration (Org.nr) for direct B2B account.',
    specialties: [
      'Master Asian food importer in Norway',
      'Rice varieties, flour, coconut milk, sauces',
      'Extensive spices & seasonings in wholesale cartons',
      'Authentic canned goods & noodles',
    ],
    paymentTerms: 'B2B invoice (14 days) after credit approval, or advance prepayment.',
    mapsUrl: 'https://maps.google.com/?q=Stanseveien+27+0976+Oslo',
    website: 'https://www.scanasia.no',
    recommendedFor: 'Best for volume purchasing of spices in master display cartons, cooking pastes, and coconut products.',
  },
  {
    id: 'deva-gruppen',
    name: 'Deva Gruppen AS / Deva Foods',
    categoryBadge: 'Dedicated Indian Brands Importer',
    address: 'Økernveien 147, 0580 Oslo',
    area: 'Økern, Oslo',
    phone: '+47 22 65 05 00',
    email: 'post@devagruppen.no',
    openingHours: 'Mon–Fri: 09:00–17:00',
    moqNotes: 'Carton quantities. Regular supplier of Indian food retail stores in Oslo.',
    specialties: [
      'Official importer of Aashirvaad Atta',
      'MDH & Everest Masalas (full cases)',
      'Haldiram Namkeens & Sweets',
      'Priya & Mother’s Recipe Pickles in glass jars',
    ],
    paymentTerms: 'Card, Vipps, or B2B invoice by agreement.',
    mapsUrl: 'https://maps.google.com/?q=Økernveien+147+0580+Oslo',
    website: 'https://devagruppen.no',
    recommendedFor: 'Best for authentic branded Indian items: MDH masala master boxes, Haldirams snacks, and glass-bottle pickles.',
  },
  {
    id: 'asia-engros',
    name: 'Asia Engros AS',
    categoryBadge: 'Ethnic Food Wholesaler',
    address: 'Oslo, Norway',
    area: 'Oslo Region',
    phone: '+47 22 30 11 00',
    email: 'post@asiaengros.no',
    openingHours: 'Mon–Fri: 08:30–16:30',
    moqNotes: 'Wholesale deliveries to grocery stores, restaurants, and catering kitchens.',
    specialties: [
      'Basmati rice in bulk sacks',
      'Spice blends and whole spices',
      'Cooking oils (sunflower, rapeseed, mustard)',
      'Pulses, beans, and lentils',
    ],
    paymentTerms: 'B2B invoice.',
    mapsUrl: 'https://maps.google.com/?q=Asia+Engros+AS+Oslo',
    website: 'https://asiaengros.no',
    recommendedFor: 'Solid backup supplier for rice, cooking oils in 5L cans, and bulk lentils.',
  },
  {
    id: 'afood-wholesale',
    name: 'A-Food Market Wholesale (Vinh Phat AS)',
    categoryBadge: 'Cash & Carry / Wholesale Hub',
    address: 'Stanseveien 25, 0976 Oslo (Wholesale) & Osterhaus’ gate 8 (Central Oslo)',
    area: 'Alnabru & Downtown, Oslo',
    phone: '+47 22 25 88 88',
    email: 'ordre@afood.no',
    openingHours: 'Mon–Sat: 09:00–19:00, Sun: 11:00–18:00',
    moqNotes: 'Both warehouse wholesale at Stanseveien and bulk store purchasing at Osterhaus gate.',
    specialties: [
      'Large sacks of rice, flour, and sugar',
      'Commercial catering cooking oils (5L & 10L cans)',
      'Fresh bulk vegetables in crates (onions, garlic, ginger)',
      'Asian sauces and dry groceries',
    ],
    paymentTerms: 'Card, Vipps, and corporate B2B invoice.',
    mapsUrl: 'https://maps.google.com/?q=Stanseveien+25+0976+Oslo',
    website: 'https://afood.no',
    recommendedFor: 'Best for 5kg/10kg produce sacks (Red Onions, Potatoes, Garlic, Ginger) and 5L cooking oils.',
  },
];
